volumes:
  meetup-data:
    external: true
services:
  fastapi:
    build:
      context: meetup
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: $${process.env.SIGNING_KEY}
      WAIT_HOSTS: db:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: mongodb://meetup_user:meetup_pw@db/admin
      PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./meetup:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_USER_SERVICE_API_HOST: http://localhost:8000

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_PASSWORD: meetup_pw
      MONGO_INITDB_ROOT_USERNAME: meetup_user
    volumes:
      - meetup-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: meetup_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: meetup_pw
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 15
      WAIT_TIMEOUT: 60
